USE `kiy-servo`;

DELIMITER $$
DROP TRIGGER IF EXISTS ZONES_AFTER_DELETE$$
CREATE DEFINER = CURRENT_USER TRIGGER `ZONES_AFTER_DELETE` AFTER DELETE ON `zones` FOR EACH ROW
BEGIN
	INSERT INTO `deletes` (`id`,`type`,`name`,`created`) VALUES (OLD.`id`,'ZONE',OLD.`name`,NOW());
END$$
DELIMITER ;

DELIMITER $$
DROP TRIGGER IF EXISTS DEVICES_AFTER_DELETE$$
CREATE DEFINER = CURRENT_USER TRIGGER `DEVICES_AFTER_DELETE` AFTER DELETE ON `devices` FOR EACH ROW
BEGIN
	INSERT INTO `deletes` (`id`,`type`,`name`,`created`) VALUES (OLD.`id`,'DEVICE',OLD.`name`,NOW());
END$$
DELIMITER ;

DELIMITER $$
DROP TRIGGER IF EXISTS TASKS_AFTER_DELETE$$
CREATE DEFINER = CURRENT_USER TRIGGER `TASKS_AFTER_DELETE` AFTER DELETE ON `tasks` FOR EACH ROW
BEGIN
	INSERT INTO `deletes` (`id`,`type`,`name`,`created`) VALUES (OLD.`id`,'TASK',OLD.`name`,NOW());
END$$
DELIMITER ;

DELIMITER $$
DROP TRIGGER IF EXISTS USERS_AFTER_DELETE$$
CREATE DEFINER = CURRENT_USER TRIGGER `USERS_AFTER_DELETE` AFTER DELETE ON `users` FOR EACH ROW
BEGIN
	INSERT INTO `deletes` (`id`,`type`,`name`,`created`) VALUES (OLD.`id`,'USER',OLD.`name`,NOW());
END$$
DELIMITER ;

DELIMITER $$
DROP TRIGGER IF EXISTS ROLES_AFTER_DELETE$$
CREATE DEFINER = CURRENT_USER TRIGGER `ROLES_AFTER_DELETE` AFTER DELETE ON `roles` FOR EACH ROW
BEGIN
	INSERT INTO `deletes` (`id`,`type`,`name`,`created`) VALUES (OLD.`id`,'ROLE',OLD.`name`,NOW());
END$$
DELIMITER ;

DELIMITER $$
DROP TRIGGER IF EXISTS SCENES_AFTER_DELETE$$
CREATE DEFINER = CURRENT_USER TRIGGER `SCENES_AFTER_DELETE` AFTER DELETE ON `scenes` FOR EACH ROW
BEGIN
	INSERT INTO `deletes` (`id`,`type`,`name`,`created`) VALUES (OLD.`id`,'SCENE',OLD.`name`,NOW());
END$$
DELIMITER ;