@ECHO OFF
CLS
ECHO Start install service ...

SET DIR=%CD%

SET PR_DESCRIPTION=KIY Servo Service
SET PR_DISPLAYNAME=KIY-SERVO

SET PR_INSTALL=%DIR%\kiy-servo.exe //IS//kiy-servo
SET PR_STARTUP=auto

SET PR_JAVAHOME=%DIR%\java
SET PR_LIBRARYPATH=%DIR%
SET PR_JVM=%PR_JAVAHOME%\jre\bin\server\jvm.dll
SET PR_CLASSPATH=%DIR%\kiy-servo.jar
SET PR_JVMOPTIONS=-Dfile.encoding=UTF-8
SET PR_JVMMS=256
SET PR_JVMMX=1024
SET PR_JVMSS=1024

SET PR_STARTMODE=jvm
SET PR_STARTPATH=%DIR%
SET PR_STARTCLASS=com.kiy.servo.Service
SET PR_STARTMETHOD=start
SET PR_STARTPARAMS=START
SET PR_STOPMODE=jvm
SET PR_STOPPATH=%DIR%
SET PR_STOPCLASS=com.kiy.servo.Service
SET PR_STOPMETHOD=stop
SET PR_STOPPARAMS=STOP
SET PR_STOPTIMEOUT=30

SET PR_LOGPATH=%DIR%\log
SET PR_LOGPREFIX=svc
SET PR_LOGLEVEL=Info
SET PR_LOGJNIMESSAGES=1
SET PR_STDOUTPUT=\log\out.log
SET PR_STDERROR=\log\err.log
SET PR_PIDFILE=pid

%PR_INSTALL%

ECHO Service installed completed
PAUSE